### ISSUE TITLE
full screen lyrics

### ISSUE THREAD

**Issue by soberup** [KJY26/Cider_Lyrics#1]
Encountered an error when displaying full screen lyrics.
![2022-07-14](https://user-images.githubusercontent.com/65408232/178979206-00d3caf6-4766-481e-893f-ccb8c9ad90a0.png)

**Comment by KJY26** [comment]
I found out it's an inline playlists problem I'll try to fix it

**Comment by KJY26** [comment]
It's been fixed! 
Update to the latest version
